require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Bundler/DuplicatedGem:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Layout/HashAlignment:
  EnforcedColonStyle: table

Metrics/BlockLength:
  Max: 35

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Style/Documentation:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/NamedSubject:
  Enabled: False
