name: Ruby

on: [push]

jobs:
  build:
    env:
      PUPPET_GEM_VERSION: "~> 7.24.0"
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7]
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: test with Rake
      run: |
        bundle exec rake spec
