name: Ruby

on: [push]

jobs:
  build:
    env:
      PUPPET_GEM_VERSION: "~> 6.10.0"
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.7]
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: test with Rake
      run: |
        bundle exec rake spec
